version: "3"

dotenv:
  - .env.task

tasks:
  build:
    desc: Gradle build
    cmds:
      - gradle clean build

  kdoc:
    desc: Kdoc build
    cmds:
      - gradle dokkaHtml

  publish:
    desc: Publish to Maven Central
    cmds:
      - gradle publishToMavenCentral
